language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/myavo

node_js:  
  - 12

before_script:
  - psql -c 'create database  myavo;' -U postgres
  - psql -U postgres -d myavo -a -f ./sql/tables.sql
  - psql -U postgres -d myavo -a -f ./sql/data.sql

services:
  - postgresql